### PR TITLE
Do not crash property if no counter example was returned

### LINKED ISSUE #133: Using `PropCheck.TargetedPBT.exists/2` causes a crash
The `PropCheck.TargetedPBT.exists/2` causes a crash when it returns false.
```Elixir
  property "`exist` crashes on false" do
    exists p <- false do
      p
    end
  end
```
crashes with:
```
  1) property `exist` crashes on false (PropCheck.Test.TargetPathTest)
     test/targeted_path_test.exs:65
     ** (CaseClauseError) no case clause matching: false
     code: property "`exist` crashes on false" do
     stacktrace:
       (propcheck) lib/properties.ex:190: PropCheck.Properties.handle_check_results/5
       test/targeted_path_test.exs:65: (test)
```

### PR DESCRIPTION
**Pull request by evnu**
This fixes the clause error found by @x4lldux when the `exists/2` macro fails.

Fix #133

### CODE REVIEW

**Comment by alfert** [comment]
Credo thinks that you introduced one branch too much to comprehend the function :-) 

Perhaps some refactoring should be advisable (e.g. inside the credo configuration or event the Elixir source code).

**Comment by evnu** [comment]
Refactored and rebased.

File: lib/properties.ex [hunk 1]
```diff
@@ -186,52 +186,92 @@ defmodule PropCheck.Properties do
...
+        |> add_additional_output(opts),
+      expr: nil
+  end
+
+  defp handle_check_results(
+         {:rerun_failed, counter_example},
+         name,
+         opts,
+         _should_fail,
+         _store_counter_example?
```
Comment (x4lldux) [inline lib/properties.ex]: Maybe should_fail & store_counter_example? should be moved to a map? In most clauses they are not used. Would make code clearer.

Comment (evnu) [reply lib/properties.ex]: Good idea. I was wondering how to make this a little bit prettier.

Comment (evnu) [reply lib/properties.ex]: Maybe it would even make sense to put all arguments into a map? We can still match on those parts which are needed? @alfert What do you think?

Comment (evnu) [reply lib/properties.ex]: I went ahead and turned all arguments into a map with ecc7a08. What do you think, is this better?

Comment (x4lldux) [reply lib/properties.ex]: I would extract `result` as a separate argument and keep the pipe flow.

Comment (evnu) [reply lib/properties.ex]: Introduced the pipe again with fe8ed8e.

Comment (x4lldux) [reply lib/properties.ex]: Looks nice.

Comment (evnu) [reply lib/properties.ex]: The pipeline failed again in targeted pbt. :man_shrugging:

Comment (x4lldux) [reply lib/properties.ex]: It's a flaky test, no worries.  I have fix for that in a PR I'll submit later.

Comment (alfert) [reply lib/properties.ex]: Oh cool, I am very interested into this "take this, flaky test" PR!

Good work, by the way!

**Comment by alfert** [comment]
Do you consider this as done?

File: lib/properties.ex (hunk 1 above)
Comment (x4lldux) [reply lib/properties.ex]: @alfert don't be ;) It's an _"engineering"_ solution, not a _"scientific"_ one.

**Comment by evnu** [comment]
> Do you consider this as done?

I think so, but apparently the test coverage for `handle_check_results/2` is not very high when running `mix test --cover --exclude will_fail:true --exclude unstable_test:true`, so I might have missed something during refactoring. So, a review of that is important.

**Comment by x4lldux** [comment]
Looks OK, I didn't see anything missed in it.

**Comment by alfert** [comment]
Then let's merge. Thanks again for your work!
